### ISSUE TITLE
"Unable to resolve a valid GraphQLSchema." when using makeExecutableSchema

### ISSUE THREAD

**Issue by majkelmichel** [apollographql/apollo#1123]
When using makeExecutableSchema function to create a schema for apollo-server to run I get the following error:

```
C:\Users\michz\WebstormProjects\debt_calculator\backend\node_modules\apollo-server-core\dist\ApolloServer.js:169
            throw new Error("Unexpected error: Unable to resolve a valid GraphQLSchema.  Please file an issue with a reproduction of this error, if possible.");
            ^

Error: Unexpected error: Unable to resolve a valid GraphQLSchema.  Please file an issue with a reproduction of this error, if possible.
    at new ApolloServerBase (C:\Users\michz\WebstormProjects\debt_calculator\backend\node_modules\apollo-server-core\dist\ApolloServer.js:169:19)
    at new ApolloServer (C:\Users\michz\WebstormProjects\debt_calculator\backend\node_modules\apollo-server-express\dist\ApolloServer.js:60:9)
    at new ApolloServer (C:\Users\michz\WebstormProjects\debt_calculator\backend\node_modules\apollo-server\dist\index.js:34:9)
    at Object.<anonymous> (C:\Users\michz\WebstormProjects\debt_calculator\backend\index.js:21:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
Reproduction (code I use):

schema.js:
```
const { typeDefs: User } = require('./user');

const Query = gql`
	type Query {
		_empty: String
    }
	
	type Mutation {
		_ : Boolean
	}
	`;

const resolvers = {
	Mutation: {
		_: () => {
			return false;
		}
	}
};

const schema = makeExecutableSchema({
	typeDefs: [ Query, User ],
	resolvers: resolvers
});

module.exports = {
	schema
}
```

user.js:
```
const { gql, UserInputError } = require('apollo-server');
const bcrypt = require('bcrypt');

const typeDefs = gql`
	type User {
		username: String!
		id: ID!
	}
	
	extend type Query {
		me: User
	}
	
	type Token {
		value: String!
	}
	
	extend type Mutation {
		login(
			username: String!
			password: String!
		): Token
	}
`;

const resolvers = {
	Query: {
		me: (root, args, context, info) => {
			return context.currentUser;
		}
	},
	Mutation: {
		login: (...)
	}
};

module.exports = {
	typeDefs,
	resolvers
}
```

index.js:
```
const { ApolloServer } = require('apollo-server');
const schema = require('./schemas/schema');
(...)
const server = new ApolloServer({
	schema: schema,
	context: (...)
})

server.listen().then(({ url }) => {
	console.log(`Server ready at ${url}`);
});
```

How can I fix this error?
Or is there any other way to modularize my GraphQL schema definitions than makeExecutableSchema?

**Comment by majkelmichel** [comment]
The error was caused by wrong import of schema. The error message could be better though
