### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by NitroBAY** [apollographql/apollo#77]
Hello, I tried to follow [this](https://blog.meteor.com/create-a-simple-hello-world-app-with-meteor-and-apollo-64bab66a456f#.8ccwzg4e2) but npm complains about UNMET PEER DEPENDENCY. I tried deleting node_modules + `npm cache clean` + `npm i`, reinstall every packages, update npm to the last version.

```
npm i --save apollo-client apollo-server express graphql graphql-tools body-parser
32-PHARMACIE-METEOR@ C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR
+-- apollo-client@0.9.0
+-- apollo-server@0.3.3
+-- body-parser@1.16.1
+-- express@4.14.1
+-- UNMET PEER DEPENDENCY graphql@0.9.1
+-- graphql-tools@0.10.0
`-- UNMET PEER DEPENDENCY react-dom@^0.14.7 || ^15.0.0
```

So I installed react-dom : 
```
npm i --save graphql@0.9.1
32-PHARMACIE-METEOR@ C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR
`-- UNMET PEER DEPENDENCY graphql@0.9.1
```
And other peer dependencies  :
```
npm i --save graphql@0.9.1 apollo-client@0.9.0
32-PHARMACIE-METEOR@ C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR
+-- UNMET PEER DEPENDENCY apollo-client@0.9.0
`-- UNMET PEER DEPENDENCY graphql@0.9.1
```

And here's the problem, whatevs I do npm complains of `UNMET PEER DEPENC[IES]` where's the dependencies are apollo-client and graphql.
What's going on ? I've seen someone on the comment of the tuto I followed having the same problem as me, people on SO complaining about this problem etc.

**Comment by NitroBAY** [comment]
`Meteor run` logs 
```
WARNING: npm peer requirements (for apollo) not installed:
W20170227-23:22:53.631(1)? (STDERR)  - graphql-server-express@^0.5.0 || ^0.6.0 not installed.
W20170227-23:22:53.631(1)? (STDERR)
W20170227-23:22:53.631(1)? (STDERR) Read more about installing npm peer dependencies:
W20170227-23:22:53.632(1)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20170227-23:22:53.632(1)? (STDERR)
W20170227-23:22:53.649(1)? (STDERR) C:\Users\Ilan Schemoul\AppData\Local\.meteor\packages\meteor-tool\1.4.3_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20170227-23:22:53.649(1)? (STDERR)                                             throw(ex);
W20170227-23:22:53.650(1)? (STDERR)                                             ^
W20170227-23:22:53.650(1)? (STDERR)
W20170227-23:22:53.650(1)? (STDERR) Error: Can't find npm module 'graphql-server-express'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170227-23:22:53.651(1)? (STDERR)     at Object.require (C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR\.meteor\local\build\programs\server\boot.js:200:17)
W20170227-23:22:53.651(1)? (STDERR)     at options.fallback (packages\modules-runtime.js:479:18)
W20170227-23:22:53.652(1)? (STDERR)     at Module.require (packages\modules-runtime.js:126:16)
W20170227-23:22:53.652(1)? (STDERR)     at Module.Mp.import (C:\Users\Ilan Schemoul\AppData\Local\.meteor\packages\modules\0.7.9\npm\node_modules\reify\lib\runtime.js:75:16)
W20170227-23:22:53.653(1)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.main-server.js (packages/apollo/main-server.js:1:291)
W20170227-23:22:53.653(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:197:9)
W20170227-23:22:53.654(1)? (STDERR)     at require (packages\modules-runtime.js:120:16)
W20170227-23:22:53.654(1)? (STDERR)     at C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR\.meteor\local\build\programs\server\packages\apollo.js:461:15
W20170227-23:22:53.655(1)? (STDERR)     at C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR\.meteor\local\build\programs\server\packages\apollo.js:467:3
W20170227-23:22:53.655(1)? (STDERR)     at C:\Easy_16.1.1\eds-www\32-PHARMACIE_METEOR\.meteor\local\build\programs\server\boot.js:303:34
```

**Comment by NitroBAY** [comment]
Okay sorry my bad I should have read warns that usually doesn't matter not the red "UNMET PEER DEPENDENCY". `UNMET PEER DEPENDENCY graphql@0.9.1` means that the problem is that I have 0.9.1 not that I don't have graphql@0.9.1.
 I looked at the bottom and find the real explanation of the problem 
`npm WARN apollo-server@0.3.3 requires a peer of graphql@^0.6.1 || ^0.7.0 but none was installed.`
Sorry again (but this npm error was quite confusing).
